[package]
name = "flx"
version = "0.3.0-beta.1"
edition = "2021"
license = "MIT"
description = "Fast proxy scraper & validator."
repository = "https://github.com/mzyui/flx"
readme = "README.md"

[profile.dev]
opt-level = 0
debug = "line-tables-only"
incremental = true

[profile.dev.package."*"]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 4
strip = true

[profile.test]
opt-level = 0
debug = "line-tables-only"

[profile.test.package."*"]
opt-level = 1

[dependencies]
anyhow = "1.0.93"
tokio = { version = "1.41.1", features = [
  "io-util",
  "rt-multi-thread",
  "sync",
  "fs",
  "net",
  "time",
  "macros",
  "signal",
] }
log = { version = "0.4.22", optional = true, features = ["std"] }

async-trait = "0.1.83"
clap = { version = "4.5", optional = true, features = ["derive"] }
maxminddb = "0.30.0"
serde = { version = "1.0.215", features = ["derive", "rc"] }
serde_json = "1.0.133"
toml = "0.8"
futures-util = "0.3"
memchr = "2.8.3"
hashbrown = "0.17.1"

# request client
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = [
  "client",
  "client-legacy",
  "http1",
] }
http-body-util = "0.1.2"
httparse = "1.9.5"
hyper-rustls = { version = "0.27", default-features = false, features = [
  "http1",
  "native-tokio",
  "aws-lc-rs",
  "tls12",
] }
rustls = "0.23"
tokio-rustls = "0.26"
rustls-native-certs = "0.8"
rustls-pemfile = "2"
webpki-roots = "0.26"
scraper = "0.27.0"
regex = "1.13.1"
base64 = "0.23.0"
url = "2.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/cli/main.rs"
name = "flx"
required-features = ["clap"]


[features]
default = ["log", "progress_bar", "clap"]
log = ["dep:log"]
progress_bar = []
clap = ["dep:clap"]
